#!/bin/bash
cd ${0%/*} || exit 1 # Run from this directory

# Source PATO run functions
. $PATO_DIR/src/applications/utilities/runFunctions/RunFunctions

# Initialize the script
pato_init

# create volume fields
rm -rf 0.000000
cp -rf origin.0 0.000000

# generate meshes
splitMeshRegions -cellZones -overwrite

# run PATOx
PATOx

#------------------------------------------------------------------------------
